/*
 * Integration Hub API
 * This API is used to create the items necessary for the SkyHive IntegrationHub product to consume
 *
 * OpenAPI spec version: 1.0.1
 * Contact: fred@skyhive.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The EnabledIntegration model module.
 * @module model/EnabledIntegration
 * @version 1.0.1
 */
export class EnabledIntegration {
  /**
   * Constructs a new <code>EnabledIntegration</code>.
   * @alias module:model/EnabledIntegration
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>EnabledIntegration</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/EnabledIntegration} obj Optional instance to populate.
   * @return {module:model/EnabledIntegration} The populated <code>EnabledIntegration</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new EnabledIntegration();
      if (data.hasOwnProperty('object'))
        obj._object = ApiClient.convertToType(data['object'], 'String');
      if (data.hasOwnProperty('cron'))
        obj.cron = ApiClient.convertToType(data['cron'], 'String');
      if (data.hasOwnProperty('module'))
        obj.module = ApiClient.convertToType(data['module'], 'String');
      if (data.hasOwnProperty('direction'))
        obj.direction = ApiClient.convertToType(data['direction'], 'String');
      if (data.hasOwnProperty('updatedFrom'))
        obj.updatedFrom = ApiClient.convertToType(data['updatedFrom'], 'String');
      if (data.hasOwnProperty('updatedThrough'))
        obj.updatedThrough = ApiClient.convertToType(data['updatedThrough'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} _object
 */
EnabledIntegration.prototype._object = undefined;

/**
 * @member {String} cron
 */
EnabledIntegration.prototype.cron = undefined;

/**
 * @member {String} module
 */
EnabledIntegration.prototype.module = undefined;

/**
 * @member {String} direction
 */
EnabledIntegration.prototype.direction = undefined;

/**
 * @member {String} updatedFrom
 */
EnabledIntegration.prototype.updatedFrom = undefined;

/**
 * @member {String} updatedThrough
 */
EnabledIntegration.prototype.updatedThrough = undefined;

