/*
 * Integration Hub API
 * This API is used to create the items necessary for the SkyHive IntegrationHub product to consume
 *
 * OpenAPI spec version: 1.0.1
 * Contact: fred@skyhive.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {PartnerSystem} from './PartnerSystem';

/**
 * The UserInterfaceState model module.
 * @module model/UserInterfaceState
 * @version 1.0.1
 */
export class UserInterfaceState {
  /**
   * Constructs a new <code>UserInterfaceState</code>.
   * @alias module:model/UserInterfaceState
   * @class
   * @extends Object
   */
  constructor() {
  }

  /**
   * Constructs a <code>UserInterfaceState</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UserInterfaceState} obj Optional instance to populate.
   * @return {module:model/UserInterfaceState} The populated <code>UserInterfaceState</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new UserInterfaceState();
      ApiClient.constructFromObject(data, obj, 'PartnerSystem');
    }
    return obj;
  }
}
